language: node_js
node_js:
  - "8"

before_install:
  - npm i -g npm@5.6.0

before_deploy:
  - "npm install && npm run build:prod"
  - "echo 'ready!'"

deploy:
  provider: releases
  strategy: git
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: artifacts/berrywallet-*
  skip_cleanup: true
  node_js: "8"
  on:
    tags: true
