language: node_js
node_js:
  - "8"

before_install:
  - npm i -g npm@5.6.0

script:
  - npm install
  - npm run build:prod

before_deploy:
  - "echo 'ready to Deploy!'"

deploy:
  provider: releases
  strategy: git
  api_key:
    secure: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: artifacts/berrywallet-*
  skip_cleanup: true
  node_js: "8"
  on:
    repo: berrywallet/berrywallet-extension
    tags: true