language: node_js

sudo: required

before_install:
  - npm i -g npm@5.6.0

before_deploy:
  - "npm install && npm run build:prod"
  - "echo 'ready!'"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: artifacts/berrywallet-*
  skip_cleanup: true
  on:
    tags: true
