language: node_js

branches:
  only:
    - /^v.*$/

node_js:
  - "8"

before_install:
  - npm i -g npm@5.6.0

install:
  - npm install
  - npm run build:prod

script:
  - echo 'Successful installed!'

before_deploy:
  - echo 'ready to Deploy!'

deploy:
  provider: releases
  strategy: git
  api_key:
    secure: bOi+koPMB4HlhlehxBha73BmB5lPLk1Nm9CUYCV8xSbPNw6T92aKsbDWumfEj1S3GRwIjHm0o7WvA5G8rW4vNMFk4gA9lSAwHNG+3nWiW28ENdzi4ZsE/N0kDvorAc/TH4txJaiicymV/BAY9A+dkS0fs+s2XJDpY0vYytHFq6ZaVc/wAQRQ2e+j2ZG3x1iqrjAZOJUgi7uqHsRRm0Z0C75YsPldShC1J7iLjIv8YG9B6w/JZV0UWseK0sjPHweHgYcHUpGwfE3UBLLju7gHBmOZ2/o8dhCde9AsYE6lg1LslZ+Tky2zter/QejSW+Tbo3v8oma8AFs0K7pvjg8OooZl6k5r2Sb3IsEnWXcAS2Bukm2gPD5NwDT223OvuTyG/mAjOiEowPcs6MgbLRYrgUZdnX434jfgVouwR3OMa6an+PvEoW+t/glrfTQS0nfVERG5uBi/ZK7xmAQz9gmEIJunHslpjHd5JcrRZLwffFd1Sfxaw+q2oeym/OtkY+WLr0AXBR1lKmKT8aBpj9wqNRFktdzlHPcrnoi5xYo9w0i4yEPxo2AttRxpplFGgswENzdvBsQKyFj1a5DscfZKsJedZAmmzapFT8aUCjDBz+THFkdHKPgY6Cz/eDNDxQFstOhePfK38ielyt04j8RqtBtqgmPy6bc3+vEpbC4w+0Y=
  file_glob: true
  file: artifacts/berrywallet-*
  skip_cleanup: true
  node_js: "8"
  on:
    repo: berrywallet/berrywallet-extension
    tags: true